### ISSUE TITLE
Stream ended unexpectedly with status null and empty body

### ISSUE THREAD

**Issue by RodolfoGS** [parse-community/node-apn#81] opened 2021-08-09 21:55 UTC
Hi, I'm having this issue randomly when I try to send a notification. Sometimes works, and sometimes I have this error. Anyone know that could be happening?

```
apn error: Request error: Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: Client network socket disconnected before secure TLS connection was established)
apn error: Session error: Error: Client network socket disconnected before secure TLS connection was established
apn error: Session closed
stream ended unexpectedly with status null and empty body
```

I'm using the version `4.1.1` and I tried upgrading to the `5.0.0`, but the issue continues.

I catched this errors adding my custom logger.
Logger:
```
const provider = new apn.Provider(config.apns);

const infoLogger = provider.client.logger;
const errorLogger = (message) => { console.log(`apn error: ${message}`); };  // logger is declared elsewhere
errorLogger.enabled = true; // required to emulate npm debug module's interface

provider.client.setLogger(infoLogger, errorLogger);
```

**Comment by davimacedo** [comment] 2021-08-10 01:01
Is it happening on your production server or your local machine? Any chance your internet connection is hanging?

**Comment by RodolfoGS** [comment] 2021-08-10 01:51
Happen on production servers on AWS. So, I think that internet is good there

**Comment by TysonAndre** [comment] 2021-08-10 02:05
> `const provider = new apn.Provider(config.apns);`

Can you provide more details about what that config is? As much detail, e.g. are proxies being used, what keys and what values (where not credentials), etc.

What node.js version are you using in AWS?


How many notifications per second? What is the typical cpu usage for node in that application (e.g. if it's close to 100% or there's a high cpu time per tick requests might time out)

How often does this happen per hour in a single process?
Are there also error messages about reconnecting?

Is this a long-lived application or a short-lived script (not sure if it'd matter, but lambda seems to have had issues in other web servers for reasons I'm not familiar with)? https://github.com/aws/aws-sdk-js/issues/3591 mentions a similar error message in a completely different context

**Comment by RodolfoGS** [comment] 2021-08-10 02:29
Ok, I'll provide you that information below.

> Can you provide more details about what that config is? As much detail, e.g. are proxies being used, what keys and what values (where not credentials), etc.

My `config.apns` content. I'm not using proxy.
```
// p8 certificate
const key = `
-----BEGIN PRIVATE KEY-----
xxxxxxxx
-----END PRIVATE KEY-----
`;

export default {
  token: {
    key,
    keyId: 'xxxxxx',
    teamId: 'xxxxxx',
  },
  production: true,
  requestTimeout: 15000,
};
```

> What node.js version are you using in AWS?

`nodejs: v14.17.3`

> How many notifications per second? What is the typical cpu usage for node in that application (e.g. if it's close to 100% or there's a high cpu time per tick requests might time out)

About ~40/second notifications.
CPU usage: I don't know since I'm running the script on Lambda and I haven't that information.

> How often does this happen per hour in a single process?

Sometimes could pass a couple of days without any issue. And sometimes, like today (Aug 9th, 2021), about 5 times along the day.

> Are there also error messages about reconnecting?

Mmmm no, I didn't see any error related to reconnecting. But sometimes, the error is a timeout error instead the mentioned in the issue (`apn write timeout`)

> Is this a long-lived application or a short-lived script (not sure if it'd matter, but lambda seems to have had issues in other web servers for reasons I'm not familiar with)? aws/aws-sdk-js#3591 mentions a similar error message in a completely different context

short-time and I running the script on Lambda, I'll check that issue

**Comment by RodolfoGS** [comment] 2021-08-10 02:36
Are any function to reconnect the client/provider when I detect that error? Or this happen be automatically?

**Comment by CallMeLaNN** [comment] 2021-12-16 07:06
I can reproduce this issue using latest version in this environment:

- Local macos: always working for node v14 and v16
- AWS node v16: working
- AWS node v14: Stream ended unexpectedly with status null and empty body

The AWS I was deploying in a docker container behind LB.

**Comment by RodolfoGS** [comment] 2021-12-16 22:26
I'm using node v14 since node v16 is not supported by lambda yet

**Comment by mtrezza** [comment] 2022-03-27 12:36
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.

**Closed by mtrezza** 2022-03-27 12:36 UTC
